repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^data/mining/
      - id: end-of-file-fixer
        exclude: ^data/mining/
      - id: check-yaml
        exclude: ^data/mining/
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
        exclude: ^data/mining/
      - id: check-ast
        exclude: ^data/mining/
      - id: check-case-conflict
      - id: check-json
        exclude: ^data/mining/
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
        exclude: ^data/mining/

  # Ruff - Fast Python linter and formatter (replaces Black + Flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^data/mining/
      # Run the formatter (Black-compatible)
      - id: ruff-format
        exclude: ^data/mining/

  # isort - Import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]
        exclude: ^data/mining/

  # mypy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-requests
        args: [--config-file=mypy.ini]
        exclude: ^(data/mining/|tests/|bin/)

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [-r, src/]
        exclude: ^(data/mining/|tests/)

  # Docstring checks
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: [tomli]
        exclude: ^(data/mining/|tests/|bin/)

# Configuration for pre-commit.ci (if using)
ci:
  autofix_prs: true
  autofix_commit_msg: '[pre-commit.ci] auto fixes from pre-commit hooks'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
